### ISSUE TITLE
"{" and "|" converts wrongly

### ISSUE THREAD

**Issue by yanoak** [mapmeld/my-winresearcher#1]
Line 73: "{" should convert to ဧ http://www.fileformat.info/info/unicode/char/1027/index.htm
Right now it converts to the numeral 5 ၅
This character is used often. For example, in ဧရာဝတီ "Ayeyarwaddy"

Line 75: "|" should convert to ဠ http://www.fileformat.info/info/unicode/char/1020/index.htm
Right now it converts to the numeral 6 ၆

**Comment by mapmeld** [comment]
@yanoak ok install version 1.2.3 or refresh the webpage and you should be good

**Comment by yanoak** [comment]
@mapmeld thanks!
